import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowClockwise } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { Layout } from "../../components/Layout";
import { Eyebrow, EmptyState, StatusPill } from "../../components/ui";
import { listDlqMessages } from "../../api/adminOperations";
import { getCoupons } from "../../api/coupons";
import { getDashboardSummary, getIssueStatistics, getReconciliationReports, getSystemHealth } from "../../api/dashboard";
import { ApiError, NetworkError } from "../../api/http";
import type { CouponIssueDlqPageResponse, CouponListResponse, DashboardSummaryResponse, IssueStatisticsResponse, ReconciliationReportSummaryResponse, SystemHealthResponse } from "../../types/api";

const panel = "rounded-block border border-hairline bg-paper p-5 text-ink dark:border-white/[0.14] dark:bg-ops-surface dark:text-ops-ink md:p-7";
const fmt = (value: number) => value.toLocaleString("ko-KR");
const countStatuses = (data: IssueStatisticsResponse | null, statuses: string[]) => (data?.distribution ?? []).filter((v) => statuses.includes(v.status)).reduce((sum, v) => sum + v.count, 0);
const message = (error: unknown) => error instanceof ApiError || error instanceof NetworkError ? error.message : "대시보드 데이터를 불러오지 못했습니다.";

function SummaryCard({ label, value, tone = "neutral" }: { label: string; value: string; tone?: "neutral" | "success" | "danger" }) {
  const color = tone === "success" ? "text-[#087c13] dark:text-success" : tone === "danger" ? "text-danger" : "text-ink dark:text-ops-ink";
  return <div className="rounded-block border border-hairline bg-surface-2 p-5 dark:border-white/[0.12] dark:bg-ops-surface"><p className="text-sm font-medium text-ink/65 dark:text-ops-muted">{label}</p><strong className={`mt-2 block text-[clamp(1.7rem,3vw,2.55rem)] leading-none tabular-nums ${color}`}>{value}</strong></div>;
}

function ThroughputChart({ data }: { data: IssueStatisticsResponse }) {
  const rows = data.timeSeries, width = 720, height = 220, pad = 18;
  const max = Math.max(1, ...rows.flatMap((row) => [row.issuedCount, row.failedCount]));
  const rates = rows.map((row) => { const total = row.issuedCount + row.failedCount + row.inProgressCount; return total ? row.failedCount / total : 0; });
  const rateMax = Math.max(0.01, ...rates);
  const points = (values: number[], ceiling: number) => values.map((value, i) => `${pad + i / Math.max(values.length - 1, 1) * (width - pad * 2)},${height - pad - value / ceiling * (height - pad * 2)}`).join(" ");
  return <div><svg viewBox={`0 0 ${width} ${height}`} className="h-[245px] w-full" role="img" aria-label="최근 24시간 발급 처리량과 실패율">{[.25,.5,.75].map((r) => <line key={r} x1={pad} x2={width-pad} y1={height*r} y2={height*r} className="stroke-hairline dark:stroke-ops-border" />)}<polyline points={points(rows.map((v)=>v.issuedCount),max)} fill="none" stroke="#2379c9" strokeWidth="3"/><polyline points={points(rows.map((v)=>v.failedCount),max)} fill="none" stroke="#cf3e40" strokeWidth="3"/><polyline points={points(rates,rateMax)} fill="none" stroke="#8a5a00" strokeWidth="2" strokeDasharray="6 5"/></svg><div className="-mt-1 flex justify-between text-[11px] text-ink/50 dark:text-ops-muted">{rows.filter((_,i)=>i%4===0||i===rows.length-1).map((v)=><span key={v.bucket}>{v.bucket.slice(11,16)}</span>)}</div><div className="mt-5 flex gap-5 text-sm"><span className="text-[#2379c9]">━ 발급</span><span className="text-[#cf3e40]">━ 실패</span><span className="text-[#8a5a00]">┅ 실패율</span></div></div>;
}

function StatusDonut({ data }: { data: IssueStatisticsResponse }) {
  const success=countStatuses(data,["CONSUMED"]), retry=countStatuses(data,["PENDING","SENT","FAILED"]), dlq=countStatuses(data,["DLQ","ABANDONED"]), total=success+retry+dlq;
  const a=total?success/total*100:0, b=total?retry/total*100:0;
  const items=[{label:"성공",value:success,color:"#079516"},{label:"재시도/진행",value:retry,color:"#8a5a00"},{label:"DLQ/포기",value:dlq,color:"#cf3e40"}];
  const bg=total?`conic-gradient(#079516 0 ${a}%,#8a5a00 ${a}% ${a+b}%,#cf3e40 ${a+b}% 100%)`:"rgb(var(--c-hairline))";
  return <div className="grid gap-7"><div className="relative mx-auto h-52 w-52 rounded-full" style={{background:bg}}><div className="absolute inset-[22%] flex items-center justify-center rounded-full bg-paper text-center dark:bg-ops-surface"><span><strong className="block text-2xl">{fmt(total)}</strong><small className="text-ink/50 dark:text-ops-muted">전체 메시지</small></span></div></div><dl className="grid gap-2 text-sm">{items.map((item)=><div key={item.label} className="flex justify-between"><dt className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm" style={{background:item.color}}/>{item.label}</dt><dd>{total?(item.value/total*100).toFixed(1):"0.0"}% <span className="text-ink/45">({fmt(item.value)})</span></dd></div>)}</dl></div>;
}

function ReconciliationBars({ reports }: { reports: ReconciliationReportSummaryResponse[] }) {
  const rows=[...reports].slice(0,10).reverse(), max=Math.max(1,...rows.map((v)=>v.totalCount));
  if(!rows.length) return <p className="py-14 text-center text-ink/55 dark:text-ops-muted">아직 저장된 정합성 검증 이력이 없습니다.</p>;
  return <div><div className="flex h-44 items-end gap-3 border-b border-hairline pb-1 dark:border-ops-border">{rows.map((row)=><div key={row.reportId} className="flex h-full flex-1 items-end" title={`#${row.reportId} ${row.result} · 오류 ${row.errorCount}건`}><div className={`w-full min-w-3 rounded-t ${row.result==="MATCHED"?"bg-[#079516]":row.result==="MISMATCHED"?"bg-[#cf3e40]":"bg-[#8f8f8b]"}`} style={{height:`${Math.max(row.totalCount/max*100,8)}%`}}/></div>)}</div><div className="mt-4 flex gap-5 text-sm"><span className="text-[#079516]">■ MATCHED</span><span className="text-[#cf3e40]">■ MISMATCHED</span><span className="text-[#8f8f8b]">■ ERROR</span></div></div>;
}

export default function Dashboard() {
  const [summary,setSummary]=useState<DashboardSummaryResponse|null>(null), [statistics,setStatistics]=useState<IssueStatisticsResponse|null>(null), [dlq,setDlq]=useState<CouponIssueDlqPageResponse|null>(null), [health,setHealth]=useState<SystemHealthResponse|null>(null);
  const [coupons,setCoupons]=useState<CouponListResponse[]>([]), [couponId,setCouponId]=useState<number|null>(null), [reports,setReports]=useState<ReconciliationReportSummaryResponse[]>([]);
  const [loading,setLoading]=useState(true), [reportsLoading,setReportsLoading]=useState(false), [error,setError]=useState(""), [checkedAt,setCheckedAt]=useState<Date|null>(null);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");const results=await Promise.allSettled([getDashboardSummary(signal),getIssueStatistics(signal),listDlqMessages(0,10,signal),getSystemHealth(signal),getCoupons({},0,100,signal)]);if(signal?.aborted)return;const [a,b,c,d,e]=results;if(a.status==="fulfilled")setSummary(a.value);if(b.status==="fulfilled")setStatistics(b.value);if(c.status==="fulfilled")setDlq(c.value);if(d.status==="fulfilled")setHealth(d.value);if(e.status==="fulfilled"){setCoupons(e.value.content);setCouponId((current)=>current??e.value.content[0]?.couponId??null);}const failed=results.find((v)=>v.status==="rejected");if(failed?.status==="rejected")setError(message(failed.reason));setCheckedAt(new Date());setLoading(false);},[]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
  useEffect(()=>{if(couponId===null){setReports([]);return;}const controller=new AbortController();setReportsLoading(true);getReconciliationReports(couponId,30,controller.signal).then(setReports).catch((e)=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(message(e));}).finally(()=>{if(!controller.signal.aborted)setReportsLoading(false);});return()=>controller.abort();},[couponId]);
  const total=useMemo(()=>(statistics?.distribution??[]).reduce((sum,v)=>sum+v.count,0),[statistics]), success=countStatuses(statistics,["CONSUMED"]), dlqCount=countStatuses(statistics,["DLQ"]), latest=reports[0];
  const rate=latest?.totalCount?latest.successCount/latest.totalCount*100:latest?.result==="MATCHED"?100:null, up=health?.components.filter((v)=>v.status==="UP").length??0, componentTotal=health?.components.length??0, attention=reports.filter((v)=>v.result!=="MATCHED").length;
  return <Layout area="internal" page="dashboard">
    <section className="py-8"><div className="container-page flex flex-wrap items-end justify-between gap-4"><div><Eyebrow>내부 운영 · 실제 운영 API</Eyebrow><h1 className="mt-2">쿠폰 발급 운영 대시보드</h1><p className="mt-2 text-[18px] text-ink/70 dark:text-ops-muted">발급 처리량과 실패, 정합성, 시스템 상태를 한 화면에서 확인합니다.</p></div><div className="flex items-center gap-3">{checkedAt?<span className="text-xs text-ink/50 dark:text-ops-muted">마지막 확인 {checkedAt.toLocaleTimeString("ko-KR",{hour12:false})}</span>:null}<button type="button" disabled={loading} onClick={()=>void load()} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-ink bg-paper px-5 font-medium text-ink disabled:opacity-50 dark:border-ops-ink dark:bg-ops-bg dark:text-ops-ink"><ArrowClockwise className={loading?"animate-spin":""}/> 새로고침</button></div></div></section>
    {error?<section className="pb-4"><div className="container-page"><div className="rounded-control border border-danger/40 bg-danger/10 p-4 text-danger">{error} 관리자 인증 세션과 백엔드 실행 상태를 확인해 주세요.</div></div></section>:null}
    <section className="py-4"><div className="container-page grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><SummaryCard label="전체 발급 요청" value={statistics?fmt(total):"—"}/><SummaryCard label="발급 성공" value={statistics?fmt(success):"—"} tone="success"/><SummaryCard label="DLQ 대기" value={statistics?fmt(dlqCount):"—"} tone={dlqCount?"danger":"neutral"}/><SummaryCard label="정합성 일치율" value={rate==null?"—":`${rate.toFixed(1)}%`}/><SummaryCard label="시스템 상태" value={health?`${health.overallStatus==="UP"?"정상":health.overallStatus} ${up}/${componentTotal}`:"—"} tone={health?.overallStatus==="UP"?"success":"danger"}/></div></section>
    <section className="py-4"><div className="container-page grid gap-6 lg:grid-cols-[3fr_2fr]"><article className={panel}><h2>발급 처리량 · 실패율</h2><p className="mt-1 text-ink/55 dark:text-ops-muted">최근 24시간</p><div className="mt-5">{statistics?<ThroughputChart data={statistics}/>:<p className="py-24 text-center text-ink/50">{loading?"불러오는 중…":"데이터가 없습니다."}</p>}</div></article><article className={panel}><h2>메시지 상태 분포</h2><p className="mt-1 text-ink/55 dark:text-ops-muted">전체 기간</p><div className="mt-7">{statistics?<StatusDonut data={statistics}/>:<p className="py-24 text-center text-ink/50">{loading?"불러오는 중…":"데이터가 없습니다."}</p>}</div></article></div></section>
    <section className="py-4"><div className="container-page"><article className={panel}><div className="mb-6 flex flex-wrap justify-between gap-4"><div><h2>정합성 검증 이력</h2><p className="mt-1 text-ink/55 dark:text-ops-muted">선택한 쿠폰의 최근 검증 결과</p></div><div className="flex items-center gap-3">{attention?<StatusPill tone="warning">{attention}건 확인 필요</StatusPill>:<StatusPill tone="open">정상</StatusPill>}<select value={couponId??""} onChange={(e)=>setCouponId(Number(e.target.value))} className="min-h-10 rounded-control border border-hairline bg-paper px-3 text-sm text-ink dark:border-ops-border dark:bg-ops-bg dark:text-ops-ink">{coupons.map((v)=><option key={v.couponId} value={v.couponId}>{v.name} (#{v.couponId})</option>)}</select></div></div>{reportsLoading?<p className="py-14 text-center text-ink/50">이력을 불러오는 중…</p>:couponId===null?<EmptyState title="조회할 쿠폰이 없습니다." description="쿠폰을 생성하면 정합성 이력을 확인할 수 있습니다."/>:<ReconciliationBars reports={reports}/>}</article></div></section>
    <section className="py-4 pb-16"><div className="container-page grid gap-6 lg:grid-cols-[1.25fr_1fr]"><article className={panel}><div className="mb-5 flex justify-between"><div><h2>최근 실패 메시지</h2><p className="mt-1 text-ink/55 dark:text-ops-muted">DLQ 최신 {dlq?.content.length??0}건</p></div><Link to="/internal/failures" className="text-sm underline underline-offset-4">전체 보기</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="text-ink/55 dark:text-ops-muted"><tr><th className="pb-3">ID</th><th className="pb-3">상태</th><th className="pb-3">오류</th><th className="pb-3 text-right">시각</th></tr></thead><tbody>{(dlq?.content??[]).slice(0,5).map((v)=><tr key={v.messageId} className="border-t border-hairline-soft dark:border-ops-border-soft"><td className="py-3 font-mono">#{v.messageId}</td><td className="py-3"><StatusPill tone="danger">DLQ</StatusPill></td><td className="max-w-xs truncate py-3 font-mono text-xs">{v.lastError}</td><td className="py-3 text-right text-ink/50 dark:text-ops-muted">{new Date(v.createdAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",hour12:false})}</td></tr>)}{!loading&&!dlq?.content.length?<tr><td colSpan={4} className="py-10 text-center text-ink/50">DLQ 메시지가 없습니다.</td></tr>:null}</tbody></table></div></article>
    <article className={panel}><div className="mb-5 flex justify-between"><div><h2>시스템 헬스체크</h2><p className="mt-1 text-ink/55 dark:text-ops-muted">백엔드 컴포넌트 상태</p></div>{health?<StatusPill tone={health.overallStatus==="UP"?"open":"danger"}>{health.overallStatus}</StatusPill>:null}</div><dl className="grid gap-3">{(health?.components??[]).map((v)=><div key={v.name} className="flex justify-between border-b border-hairline-soft pb-3 last:border-0 dark:border-ops-border-soft"><dt className="font-medium capitalize">{v.name==="db"?"MySQL":v.name}</dt><dd className={v.status==="UP"?"font-semibold text-[#087c13] dark:text-success":"font-semibold text-danger"}>{v.status}</dd></div>)}</dl>{summary?<div className="mt-6 grid grid-cols-2 gap-3 border-t border-hairline pt-5 text-sm dark:border-ops-border"><p>활성 이벤트 <strong className="float-right">{summary.activeEvents}/{summary.totalEvents}</strong></p><p>활성 쿠폰 <strong className="float-right">{summary.activeCoupons}/{summary.totalCoupons}</strong></p><p>발급 재고 <strong className="float-right">{fmt(summary.startedCouponIssuedStock)}</strong></p><p>잔여 재고 <strong className="float-right">{fmt(summary.startedCouponRemainingStock)}</strong></p></div>:null}</article></div></section>
  </Layout>;
}
